litellm_settings:
  drop_params: true
  request_timeout: 600
  modify_params: true
  enable_json_schema_validation: false
  callbacks: custom_callbacks.drop_handler
  
general_settings:
  drop_params: true

model_list:
  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: azure/gpt-5.2-2025-12-11
      api_base: https://staging-openai.azure-api.net/openai-gw-proxy-dev
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2025-04-01-preview"
      drop_params: true

  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: azure/gpt-5-mini-2025-08-07
      api_base: https://staging-openai.azure-api.net/openai-gw-proxy-dev
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_version: "2025-04-01-preview"
      drop_params: true
